### ISSUE TITLE
Feature Request: Define size of editorCanvas

### ISSUE THREAD

**Issue by MSSandroid** [krish-adi/barfi#14]
I would like to be able to set the size of the editorCanvas. I was not able to overwrite the css with the st.markdown st.write unsafe_html trick.

**Comment by TPreece101** [comment]
I don't know if this will help with your use case, I was having trouble with the canvas being really narrow and not adjusting to the width of the page. I found that if you set `st.set_page_config(layout="wide")` then it will adjust to the width of the page quite nicely.

**Comment by MSSandroid** [comment]
I was able to set it with adding following code to the side:
```python
st.markdown(
        """
        <style>
            [title="barfi.st_barfi"] {
                height: 20vw;
            }
        </style>
        """,
        unsafe_allow_html=True,
    )
```

**Comment by krish-adi** [comment]
Thanks @TPreece101 @MSSandroid
