### ISSUE TITLE
Add support for streamlit password st.text_input type

### ISSUE THREAD

**Issue by zabrewer** [krish-adi/barfi#2]
For the st.text_input widget, streamlit supports password masking using the type='password' param (https://docs.streamlit.io/library/api-reference/widgets/st.text_input).  Any way to get support for this?

**Comment by krish-adi** [comment]
Hi @zabrewer ,

Do you mean to ask if, for the blocks, the text input could be set to mask whatever that is typed in?

**Comment by zabrewer** [comment]
Yes, you understand correctly.  I may have a work around by adding a streamlit widget (text input) and access the data from that input rather then in the barfi execution flow.

**Comment by krish-adi** [comment]
Yeah, that could be a work around.

**Comment by zabrewer** [comment]
You can close this @krish-adi - I think my work around works well.

**Comment by krish-adi** [comment]
Cool! Thanks.
