### ISSUE TITLE
"hidden" inputs/outputs?

### ISSUE THREAD

**Issue by zabrewer** [krish-adi/barfi#3]
Is there an option for hidden inputs or outputs?  meaning a default input/output that is carried down each block without the user interaction?

**Comment by krish-adi** [comment]
Hey @zabrewer,

Interesting option. Haven't actually thought about that. Do you have a specific use case in mind? So I can design the option around it.

**Comment by zabrewer** [comment]
@krish-adi - I needed to access a dynamic api_session (e.g. initial connection to an API that comes from another library) to make other calls using that connection but after testing I believe I can store the object in streamlit's st.session and access it in each downstream execution block from st.session.  

Users after the initial invitation should not see the session but I needed to re-access it rather than setting up a new TCP connection to the API every time.

I love this project and appreciate your work.
